services:
  crawler:
    build: .
    env_file:
      - ./.env
    environment:
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
      - SERVER_API_URL=http://server:3000
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    depends_on:
      - redis
      - server
    volumes:
      - ./logs:/usr/src/app/logs
      - ./web-crawling:/usr/src/app/web-crawling
    networks:
      - crawler_net

  server:
    build:
      context: ./server
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - crawler_net
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crawler_net

volumes:
  redis_data:

networks:
  crawler_net:
    driver: bridge